version: '3.8'

services:
  postgres:
    container_name: webhook-db
    image: postgres:13
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - mesx_network
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_POSTGRES_USERNAME}
      DATABASE_POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  webhook-service:
    container_name: webhook-service-production
    image: ${DOCKER_REGISTRY_HOST}/snp_smartwms/source/be/webhook-service:${NODE_ENV:-develop}
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    networks:
      mesx_network:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    ports:
      - ${APP_CONTAINER_PORT}:3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run start:prod

  webhook-migration:
    image: ${DOCKER_REGISTRY_HOST}/snp_smartwms/source/be/webhook-service:${NODE_ENV:-develop}
    command: npm run migration:run
    depends_on:
      - postgres
    networks:
      - mesx_network

networks:
  mesx_network:
    name: ${MESX_NET_NAME}
    external: true

volumes:
  db_data: {}
