version: '3.8'

services:
  webhook-service:
    container_name: webhook-service-local
    image: webhook-service-image
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    networks:
      mesx_network:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run start:debug
    ports:
      - ${APP_CONTAINER_PORT}:3000
      - 9235:9235

  webhook-migration:
    image: webhook-service-image
    command: npm run migration:run
    networks:
      - mesx_network

networks:
  mesx_network:
    name: ${MESX_NET_NAME}
    external: true

volumes:
  db_data: {}
