version: '3.8'

services:
  webhook-service:
    container_name: webhook-service-local
    image: webhook-service-image
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    networks:
      mesx_network:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    volumes:
      - .:/app
      - webhook_node_modules:/app/node_modules
    restart: unless-stopped
    command: [ "sh", "-c", "npm run start:debug" ]
    ports:
      - ${APP_CONTAINER_PORT}:3000
      - 9235:9235

networks:
  mesx_network:
    name: ${MESX_NET_NAME}
    external: true

volumes:
  webhook_node_modules:
