#!/bin/bash

echo NODE_ENV=$NODE_ENV >> .env
echo MESX_NET_NAME=$MESX_NET_NAME >> .env
echo CONTAINER_NETWORK_IP=$CONTAINER_NETWORK_IP >> .env
echo APP_CONTAINER_PORT=$APP_CONTAINER_PORT >> .env

echo DATABASE_POSTGRES_HOST=$DATABASE_POSTGRES_HOST >> .env
echo DATABASE_POSTGRES_PORT=$DATABASE_POSTGRES_PORT >> .env
echo DATABASE_POSTGRES_USERNAME=$DATABASE_POSTGRES_USERNAME >> .env
echo DATABASE_POSTGRES_PASSWORD=$DATABASE_POSTGRES_PASSWORD >> .env
echo DATABASE_CONNECTION_LIMIT=20 >> .env

echo DATABASE_CONNECTION_TIME_OUT=150000 >> .env
echo DATABASE_ACQUIRE_TIME_OUT=150000 >> .env
echo DATABASE_CONNECTION_LIMIT=20 >> .env

echo CONSUL_HOST=$CONSUL_HOST >> .env
echo CONSULPORT=$CONSULPORT >> .env
echo CONSUL_TOKEN=$CONSUL_TOKEN >> .env

echo KONG_HOST=$KONG_HOST >> .env
echo KONG_PORT=$KONG_PORT >> .env

echo SERVICE_NAME=$SERVICE_NAME >> .env
echo API_PATH=$API_PATH >> .env

echo KAFKA_BROKERS=$KAFKA_BROKERS >> .env
echo KAFKA_GROUP_ID=$KAFKA_GROUP_ID >> .env

echo NATS_SERVERS=$NATS_SERVERS >> .env